# Generated by Django 5.1.3 on 2024-11-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('cuisine_type', models.CharField(choices=[('Italian', 'Italian'), ('Chinese', 'Chinese'), ('Indian', 'Indian')], max_length=50)),
                ('open_at', models.TimeField()),
                ('close_at', models.TimeField()),
                ('contact_info', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=500)),
                ('dish_image', models.ImageField(blank=True, upload_to='dish_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
