# Generated by Django 5.1.3 on 2024-11-15 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Restaurants', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.restaurantowner'),
        ),
        migrations.AddField(
            model_name='restaurantmenu',
            name='restaurent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurants.restaurant'),
        ),
    ]
