# Generated by Django 5.1.3 on 2024-11-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_img',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='discription',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='dish_image',
            field=models.ImageField(upload_to='dish_images/'),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='dish_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
