# Generated by Django 5.1.3 on 2024-11-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0003_restaurant_restaurant_img_alter_restaurant_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmenu',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
