# Generated by Django 5.1.3 on 2024-11-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0006_remove_cartitem_cart_remove_cartitem_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='rating',
            new_name='avg_rating',
        ),
    ]
