# Generated by Django 5.1.3 on 2024-11-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='customer_profile_imagess/'),
        ),
    ]
