# Generated by Django 5.1.3 on 2024-11-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='dish_images/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_name',
            field=models.CharField(default='item', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PLACED', max_length=10),
        ),
    ]
