# Generated by Django 5.1.3 on 2024-11-22 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0007_rename_rating_restaurant_avg_rating'),
        ('customer', '0002_alter_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Restaurants.restaurant'),
        ),
    ]
