# Generated by Django 5.1.3 on 2024-11-22 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_cart_restaurant'),
        ('users', '0002_alter_customer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_cart', to='users.customer'),
        ),
    ]
