# Generated by Django 5.1.3 on 2024-11-22 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_cart_customer'),
        ('users', '0002_alter_customer_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
