# Generated by Django 5.1.3 on 2024-11-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_order_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_recipt',
            field=models.FileField(blank=True, null=True, upload_to='order_recipt_pdf/'),
        ),
    ]
