# Generated by Django 5.1.3 on 2024-11-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField()),
                ('food_rating', models.IntegerField()),
                ('service_rating', models.IntegerField()),
                ('ambiance_rating', models.IntegerField()),
                ('likes', models.IntegerField(default=0)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('dislikes', models.IntegerField(default=0)),
            ],
        ),
    ]
