# Generated by Django 5.1.3 on 2024-11-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='review_img',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
    ]
