# Generated by Django 5.1.3 on 2024-11-19 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0004_alter_restaurantmenu_price'),
        ('Reviews', '0003_remove_review_rating_review_review_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurants.restaurant'),
        ),
    ]
