# Generated by Django 5.1.3 on 2024-11-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0006_likedislike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeDislike',
        ),
    ]
