# Generated by Django 5.1.3 on 2024-11-20 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0007_delete_likedislike'),
        ('users', '0002_alter_customer_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reviews.review')),
            ],
            options={
                'unique_together': {('customer', 'review')},
            },
        ),
    ]
