# Generated by Django 5.1.3 on 2024-11-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0008_likedislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='avg_rating',
        ),
    ]
