# Generated by Django 5.1.3 on 2024-11-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0009_remove_review_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ambiance_rating',
        ),
        migrations.AddField(
            model_name='review',
            name='delivery_time_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='order_accuracy_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='packaging_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
